sudo: required

services:
  - docker

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
# Pull dev image
- docker pull lhcopetti/haskell-game:dev
# Pull base image
- docker pull lhcopetti/haskell-game:base

# List Docker images
- docker image ls -a

# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Removes unecessary runtime dependencies and updates the version for the images
- ./normalize-stack.sh
- stack --no-terminal --install-ghc test --only-dependencies -v
- stack image container -v

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./travis-deploy.sh
  on:
    branch: master