sudo: required

services:
  - docker

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
# Error on travis:
# The following packages have unmet dependencies:
#  nvidia-docker2 : Depends: docker-ce (= 18.03.1~ce-0~ubuntu) but 18.05.0~ce~3-0~ubuntu is to be installed or
#                           docker-ee (= 18.03.1~ee-0~ubuntu) but it is not installable

# Update docker version for the nvidia-docker2
- sudo apt-get install -y docker-ce=18.05.0~ce~3-0~ubuntu

# Pull dev image
- docker pull lhcopetti/haskell-game:dev

# Install nvidia-docker2 (required to have the runtime specified in the stack.yaml)
- travis_retry curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
- distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
- travis_retry curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
- sudo apt-get -y update
# - sudo apt-get install -y nvidia-docker2

# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies -v

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./travis-deploy.sh
  on:
    branch: master