sudo: required

services:
  - docker

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
  - docker pull lhcopetti/haskell-game:dev

script:
# Build the package, its tests, and its docs and run the tests
- docker run --rm -v "$(pwd):/app/" -w "/app/" lhcopetti/haskell-game:dev stack --no-terminal test --haddock --no-haddock-deps --allow-different-user

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./travis-deploy.sh
  on:
    branch: feature/AlsoUpdateLtsDockerTagOnRelease