name:                AHaskellGame
version:             0.1.0.0
github:              "lhcopetti/AHaskellGame"
license:             MIT
author:              "Luís Copetti"
maintainer:          "lhcopetti@gmail.com"
copyright:           "2017 Luís Copetti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            An exploration of the Haskell capabilities when it comes to game programming
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/lhcopetti/AHaskellGame#readme>

dependencies:
- base >= 4.7 && < 5
- SFML
- transformers
- mtl
- random
- Hipmunk
- containers
- StateVar
- monadplus
- hspec
- ConwayLib

library:
  source-dirs: src
  ghc-options:
  - -W
  - -Werror

data-files:
- resources/**/*

executables:
  AHaskellGame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Werror
    dependencies:
    - AHaskellGame
    - ConwayLib
    other-modules:
    - Paths_AHaskellGame

  ConwaysGameOfLife:
    main:                Main.hs
    source-dirs:         conway-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Werror
    dependencies:
    - ConwayLib
    - AHaskellGame

tests:
  AHaskellGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AHaskellGame
    - hspec