#!/bin/bash

# Image Name:
VERSION="$(cat src/version.ver)"

# This image name is generated by 'stack image container'
IMAGE_NAME="lhcopetti/haskell-game:base-lts-$VERSION-AHaskellGame-exe"

LTS_IMAGE_NAME="lhcopetti/haskell-game:base-lts"
VERSIONED_LTS_IMAGE_NAME="$LTS_IMAGE_NAME-"$VERSION

docker tag "$IMAGE_NAME" "$VERSIONED_LTS_IMAGE_NAME"
docker tag "$IMAGE_NAME" "$LTS_IMAGE_NAME"

echo "$VERSIONED_LTS_IMAGE_NAME"
echo "$LTS_IMAGE_NAME"